BanHangThoiTrangMVC/Controllers/ArticleController.cs
using BanHangThoiTrangMVC.Models;
using BanHangThoiTrangMVC.Models.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanHangThoiTrangMVC.Controllers
{
    public class ArticleController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Article
        public ActionResult Index(int? page)
        {
            var pageSize = 5;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<Posts> items = db.Posts.OrderByDescending(x => x.CreateDate);
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }

        public ActionResult Detail(int id)
        {
            var item = db.Posts.Find(id);
            return View(item);
        }
    }
}

BanHangThoiTrangMVC/Views/Article/Detail.cshtml
@model BanHangThoiTrangMVC.Models.EF.Posts
@{
    ViewBag.Title = Model.SeoTitle;
    ViewBag.SeoDescription = Model.SeoDescription;
    ViewBag.SeoKeyWord = Model.SeoKeywords;
}
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/main_styles.css">
<!-- Slider -->
<style>
    .news_section_container {
        margin-top: 180px;
    }

    .row-item-new {
        margin-bottom: 20px;
    }

    .title-news {
        font-size: 24px;
        border-bottom: 1px solid;
        padding: 15px 0;
        margin-bottom: 25px;
    }

    .img-box img {
        max-width: 100%;
        max-height: 100%;
    }
</style>
<div class="container news_section_container">
    @if (Model != null)
    {
        <div class="row">
            <div class="col-md-12">
                <h1 class="title-news"> @Model.Title</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Model.Description
            </div>
            <div class="col-md-12">
                @Html.Raw(Model.Detail)
            </div>
        </div>
    }

</div>

BanHangThoiTrangMVC/Views/Article/Index.cshtml
@model PagedList.PagedList<BanHangThoiTrangMVC.Models.EF.Posts>
@using PagedList.Mvc;
@using PagedList;
@{
    ViewBag.Title = "Bài Viết";
    @*ViewBag.SeoDescription = Model.SeoDescription;
        ViewBag.SeoKeyWord = Model.SeoKeywords;*@
}

<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/main_styles.css">
<!-- Slider -->
<style>
    .news_section_container {
        margin-top: 180px;
    }

    .row-item-new {
        margin-bottom: 20px;
    }

    .title-news {
        font-size: 24px;
        border-bottom: 1px solid;
        padding: 15px 0;
        margin-bottom: 25px;
    }

    .img-box img {
        max-width: 100%;
        max-height: 100%;
    }
</style>
<div class="container news_section_container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="title-news"> Khuyến mãi</h1>
        </div>
    </div>
    @if (Model != null && Model.Any())
    {
        foreach (var item in Model)
        {
            <div class="row row-item-new">
                <div class="col-md-3">
                    <div class="img-box">
                        <a href="" title="@item.Title"><img src="@item.Image" alt="@item.Title" /></a>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="content-box">
                        <h3><a href="@Url.Action("Detail", "Article", new { id = item.Id })" title="@item.Title">@item.Title</a></h3>
                        <div class="description-box">
                            @item.Description
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="row">
            <div class="col-6"></div>
            <div class="col-6" style="text-align:right;">
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
            </div>
        </div>
    }

</div>